CREATE TABLE IF NOT EXISTS User (
    id        INTEGER PRIMARY KEY AUTOINCREMENT,
    email     STRING  UNIQUE,
    password  STRING  NOT NULL,
    firstName STRING,
    lastName  STRING,
	salt	  STRING NOT NULL
);

CREATE TABLE IF NOT EXISTS `OneOffFiles` (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`userId`	TEXT,
	`uid`	STRING NOT NULL UNIQUE,
	`filename`	TEXT NOT NULL,
	`expire`	DATETIME,
	`collected`	BOOLEAN NOT NULL DEFAULT (0),
	`collectedUserId`	INTEGER,
	`password`	STRING,
	`requireLogin`	BOOLEAN NOT NULL DEFAULT (0),
	`uploadTime`	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`downloadTime`	TIMESTAMP,
	FOREIGN KEY(`collectedUserId`) REFERENCES `User`(`id`),
	FOREIGN KEY(`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
);